pub mod bass;
pub mod fm_snap;
pub mod granulator;
pub mod hihat2;
pub mod kick;
pub mod melody;
pub mod mono_synth;
pub mod multisample;
pub(crate) mod multisample_control;
#[cfg(feature = "bounce")]
pub mod multisample_pack;
#[cfg(feature = "bounce")]
pub mod multisample_prep;
pub mod percussion_engine;
pub mod poly_synth;
pub(crate) mod poly_synth_control;
pub mod reso_kick;
pub mod resonator_voice;
pub mod sampler;
pub(crate) mod sampler_control;
pub mod snare;
pub mod tom;
pub mod tom2;
pub mod twin_core_perc;

pub use self::bass::*;
pub use self::fm_snap::*;
pub use self::granulator::*;
pub use self::hihat2::*;
pub use self::kick::*;
pub use self::melody::*;
pub use self::mono_synth::*;
pub use self::multisample::*;
#[cfg(feature = "bounce")]
pub use self::multisample_pack::*;
#[cfg(feature = "bounce")]
pub use self::multisample_prep::*;
pub use self::percussion_engine::*;
pub use self::poly_synth::*;
pub use self::reso_kick::*;
pub use self::resonator_voice::*;
pub use self::sampler::*;
pub use self::snare::*;
pub use self::tom::*;
pub use self::tom2::*;
pub use self::twin_core_perc::*;

pub type HiHat = HiHat2;
pub type HiHatConfig = HiHat2Config;
